apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spyre-precompiled-model-tp1
  namespace: llm-d-on-aiu
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client-ess
