apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vllm-spyre-nixl
  namespace: llm-d-on-aiu
  labels:
    app: vllm-spyre-nixl
    component: modelserver
spec:
  lookupPolicy:
    local: true
