apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../recipes/modelserver/base/single-host/pd/vllm

namePrefix: pd-disaggregation-ibm-aiu-vllm-

components:
  - ../../../../../recipes/modelserver/components/images/aiu-vllm

labels:
  - pairs:
      llm-d.ai/model: granite-4.2-8b
      llm-d.ai/guide: pd-disaggregation
      llm-d.ai/accelerator-variant: aiu
      llm-d.ai/accelerator-vendor: ibm
      llm-d.ai/engine-type: vllm
    includeSelectors: true
    includeTemplates: true
patches:
  - path: patch-decode-aiu-v1.yaml
  - path: patch-prefill-aiu-v1.yaml
  - path: patch-decode-routing-sidecar.yaml
  - path: patch-decode-ports.yaml
