apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  template:
    spec:
      containers:
        - name: modelserver
          ports:
            - $patch: replace
            - name: modelserver
              containerPort: 8001
              protocol: TCP
            - name: nixl
              containerPort: 5600
              protocol: TCP
