apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefill
spec:
  replicas: 1
  template:
    spec:
      schedulerName: spyre-scheduler
      nodeSelector:
        ibm.com/spyre.product: IBM_Spyre
        kubernetes.io/hostname: p1-worker-69
      initContainers:
        - name: preprocess
          image: ghcr.io/llm-d/llm-d-benchmark:v0.6.8.1
          imagePullPolicy: Always
          command:
            - set_llmdbench_environment.py
            - -e
            - /shared-config/llmdbench_env.sh
            - -i
          env:
            - name: HOME
              value: /home/vllm
            - name: XDG_CACHE_HOME
              value: /home/vllm/.cache
            - name: XDG_CONFIG_HOME
              value: /home/vllm/.config
          volumeMounts:
            - name: shared-config
              mountPath: /shared-config
            - name: preprocess-home
              mountPath: /home/vllm
      containers:
        - name: modelserver
          command:
            - /bin/bash
            - -lc
          args:
            - |
              source /opt/rh/gcc-toolset-14/enable && \
              source /home/senuser/setup-vllm-spyre-env.sh && \
              . /shared-config/llmdbench_env.sh && \
              vllm serve /model-cache/$MODEL_PATH \
              --host 0.0.0.0 \
              --served-model-name $MODEL_NAME \
              --port $VLLM_INFERENCE_PORT \
              --max-model-len $VLLM_MAX_MODEL_LEN \
              --max-num-seqs $VLLM_MAX_NUM_SEQ \
              --max-num-batched-tokens $VLLM_MAX_NUM_BATCHED_TOKENS \
              --tensor-parallel-size $TP_SIZE \
              --kv-transfer-config '{"kv_connector":"InMemorySpyreConnector", "kv_role":"kv_producer"}' \
              --disable-uvicorn-access-log \
              --disable-access-log-for-endpoints=/health,/metrics,/v1/models \
              --enable-prefix-caching \
              --dtype bfloat16
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: llm-d-hf-token
                  key: HF_TOKEN
            - name: VLLM_NIXL_SIDE_CHANNEL_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MODEL_PATH
              value: models/ibm-granite/granite-3.3-8b-instruct
            - name: MODEL_NAME
              value: ibm-granite/granite-3.3-8b-instruct
            - name: VLLM_INFERENCE_PORT
              value: "8000"
            - name: VLLM_MAX_MODEL_LEN
              value: "16384"
            - name: VLLM_MAX_NUM_SEQ
              value: "32"
            - name: VLLM_MAX_NUM_BATCHED_TOKENS
              value: "4096"
            - name: TP_SIZE
              value: "1"
            - name: HOME
              value: /tmp
            - name: USER
              value: vllm
            - name: LOGNAME
              value: vllm
            - name: TORCHINDUCTOR_CACHE_DIR
              value: /.cache/torchinductor
            - name: TRITON_CACHE_DIR
              value: /.triton
            - name: XDG_CACHE_HOME
              value: /.cache
            - name: XDG_CONFIG_HOME
              value: /.config
            - name: VLLM_HTTP_TIMEOUT_KEEP_ALIVE
              value: "120"
            - name: FLEX_COMPUTE
              value: SENTIENT
            - name: FLEX_DEVICE
              value: PF
            - name: VLLM_SPYRE_PERF_METRIC_LOGGING_ENABLED
              value: "1"
            - name: FLEX_HDMA_P2PSIZE
              value: "268435456"
            - name: FLEX_HDMA_COLLSIZE
              value: "268435456"
            - name: HF_HUB_DISABLE_XET
              value: "1"
            - name: TORCH_SENDNN_CACHE_ENABLE
              value: "1"
            - name: TORCH_SENDNN_CACHE_DIR
              value: /mnt/spyre-precompiled-model
            - name: VLLM_SPYRE_DYNAMO_BACKEND
              value: sendnn
            - name: VLLM_SPYRE_USE_CB
              value: "1"
            - name: VLLM_SPYRE_USE_CHUNKED_PREFILL
              value: "1"
            - name: VLLM_DT_CHUNK_LEN
              value: "1024"
            - name: VLLM_SPYRE_ENABLE_NIXL_TRANSFER
              value: "1"
            - name: VLLM_SPYRE_NIXL_BLOCKING_TRANSFER
              value: "0"
            - name: VLLM_SPYRE_ENABLE_KV_CONNECTOR_BRIDGE
              value: "1"
          resources:
            limits:
              cpu: "20"
              memory: 300Gi
              ibm.com/spyre_pf: "1"
            requests:
              cpu: "20"
              memory: 300Gi
              ibm.com/spyre_pf: "1"
          #  securityContext:
          #   capabilities:
          #     add:
          #       - IPC_LOCK
          #   runAsGroup: 0
          #   runAsUser: 0
          volumeMounts:
            - mountPath: /shared-config
              name: shared-config
            - mountPath: /model-cache
              name: model-cache
            - mountPath: /mnt/spyre-precompiled-model
              name: spyre-precompiled-model
            - mountPath: /dev/shm
              name: shm
            - mountPath: /.cache
              name: torch-compile-cache
            - mountPath: /.config
              name: vllm-config
            - mountPath: /.triton
              name: triton-cache
          startupProbe:
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 120
          livenessProbe:
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: shared-config
          emptyDir: {}
        - name: preprocess-home
          emptyDir: {}
        - name: model-cache
          persistentVolumeClaim:
            claimName: workload-pvc
        - name: spyre-precompiled-model
          persistentVolumeClaim:
            claimName: spyre-precompiled-model
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 20Gi
        - name: torch-compile-cache
          emptyDir: {}
        - name: vllm-config
          emptyDir: {}
        - name: triton-cache
          emptyDir: {}
