apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: spyre-vllm-custom
allowPrivilegedContainer: false
allowPrivilegeEscalation: false
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowedCapabilities:
  - IPC_LOCK
  - NET_ADMIN
  - NET_RAW
  - SYS_RAWIO
defaultAddCapabilities: []
requiredDropCapabilities: []
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
seccompProfiles:
  - runtime/default
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
users: []
groups: []
